.github/workflows/build_and_test.yml, .github/workflows/build_forks.yml
Allow forked workflow for any change and prevent running main CI for PRs coming from forks.
=> Fine-tune CI from forked repos

.github/workflows/build_and_test.yml, .github/workflows/build_forks.yml, .gitignore, README.md, scripts/fetch-compose.sh
Simplified the fetch script to download both enterprise and community compose from acs-deployment, the only argument is the version of acs-deployment.
Clarified how to leverage environment variables to test the desired built images.
OPSEXP-2915
#103
=> OPSEXP-2915 Improve compose testing docs

Makefile
Fixing bug that was causing older versions not to pick up the proper version of Tomcat. Makefile was not setting tomcat versions vars as env vars - bake could not use them.
OPSEXP-2922
=> OPSEXP-2922  Ensure Tomcat version variables are exported as environment variables in Makefile for Docker Bake

README.md
Added readme for building older versions of acs using make
OPSEXP-2922
=> OPSEXP-2922 Describe how to build older versions with make

.github/workflows/cleanup_images.yml
Added step in cleanup images workflow which cleans the bakery-cache repo from the tags older than 2 weeks when requested (scheduled job or workflow dispatch) 
ref: OPSEXP-2893
=> OPSEXP-2893 Add step which cleans the bakery-cache tags older than given period

repository/amps/README.md, share/amps/README.md, sync/README.md
Link which used to point to [docs.alfresco.com](http://docs.alfresco.com/) needs to be changed to point to [support.hyland.com](http://support.hyland.com/) 
OPSEXP-2932
=> OPSEXP-2932 Point links to support.hyland.com

README.md
It's a deprecated library and embedded in python since long time
=> Remove hashlib from docs

scripts/fetch_artifacts.py
Fix main branch build.
Refactoring in #143 gone wrong, however that handling was required in early versions of the fetch script to avoid zero-size files poisoning the cache upon failure, but now we are using a separate temp folder for downloads so should not even be necessary.
I am not sure the checksum failure is really depending on the script, however now file resources are properly closed using `with`.
OPSEXP-3098
=> OPSEXP-3098 Fixup fetch script

.github/workflows/cleanup_images.yml
We are currently deleting older tags only for the cache repository, but since we previously had a failure in cleanup of tags on pr close now we have a fair amount of tags present in every repository which could be simply deleted as we are not really publishing/using these images anywhere else.
OPSEXP-3082
=> OPSEXP-3082 Cleanup old tags from all repositories

tomcat/Dockerfile
ref https://github.com/Alfresco/alfresco-docker-base-tomcat/pull/230
OPSEXP-3032
=> OPSEXP-3032 Honor X-Forwarded-Port in RemoteIpValve

scripts/fetch_artifacts.py
artifact fetching ignores subdirectories passed as arguments
n/a
=> OPSEXP-3164: fix greedy artifact fetch helper

docker-bake.hcl
Make sure we don't build without a proper tomcat version set
OPSEXP-3185
=> OPSEXP-3185 Ensure we use tomcat defined in tomcat_versions.yml

repository/Dockerfile, share/Dockerfile
Rebuilding repository image twice will fail because `install-mmt` will halt finding an already applied amp in the final war.
OPSEXP-3247
=> OPSEXP-3247 Fixup repository amp idempotency and uniform install-mmt cmd

README.md
Add a reference to vagrant into the main readme
OPSEXP-3247
=> OPSEXP-3247 Reference Vagrantfile availability in README.

.gitignore
Make sure to gitignore files pulled while evaluating the procedure to test images on docker compose: https://github.com/Alfresco/alfresco-dockerfiles-bakery?tab=readme-ov-file#testing-with-docker-compose
OPSEXP-3247
=> OPSEXP-3247 Extend gitignore to cover compose tests

README.md, repository/amps/README.md, repository/amps_community/README.md, repository/amps_enterprise/README.md, repository/libs/README.md, repository/simple_modules/README.md, share/amps/README.md, share/simple_modules/README.md
This pull request updates the `README.md` file to improve documentation for customizing Docker images. The updates include adding a new section for customizing the Share image and clarifying the instructions for customizing the Alfresco Content Repository image.
* **Added a new section for customizing the Share image**: Introduced a detailed explanation of how to customize the Share image by placing AMPs and JAR files in specific folders. This section mirrors the structure of the Alfresco Content Repository customization section.
* **Clarified instructions for customizing the Alfresco Content Repository image**: Updated the description to specify that files should be added to "specific folders" and adjusted the formatting for better readability.
OPSEXP-3247
=> OPSEXP-3247 Improve customization documentation to cover simple jars and share image

scripts/fetch_artifacts.py
When authenticated but without access to a specific artifact, just continue.
Fix #184
=> Treat 403 while fetching packages as a soft error

README.md
Updates the `README.md` file to provide additional guidance for using Vagrant as an alternative to installing dependencies locally. It introduces a new "Vagrant alternative" section and includes detailed instructions for setting up and using the provided `Vagrantfile`.
OPSEXP-3254
=> OPSEXP-3254 add instructions for vagrant

.github/workflows/acs_reusable_build_and_test.yml, .github/workflows/test-with-bats.yml, README.md, scripts/fetch_artifacts.py, scripts/tests/test_fetch_artifacts.bats
This PR adds support for fetching artifacts using glob patterns while refactoring the target file discovery logic. Key changes include the introduction of a new function to differentiate between path and glob input, the refactoring of the artifact-finding logic in the main script, and the addition of extensive tests (using BATS) to validate various scenarios.
OPSEXP-3262
=> OPSEXP-3262 Add support for fetching artifacts by passing glob 

.github/workflows/reusable_bake_build.yml
After moving to reusable workflow I forgot to add also env `TAG` which is used by bake file. Strangely workflow passed without problems.
OPSEXP-3262
=> OPSEXP-3262 Add missing env in reusable bake workflow needed by bake file

README.md
Add an item in the release docs to manually review and update the `aps` images since they are not yet supported in the `updatecli` workflow.
OPSEXP-3348
=> OPSEXP-3348 Update release checklist to remember about aps images
